import {
  pgTable,
  uuid,
  text,
  boolean,
  timestamp,
  jsonb,
  index,
  uniqueIndex,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { knowledgeNodes } from "./knowledge_nodes.js";
import { agents } from "./agents.js";
import { authUsers } from "./auth.js";

/**
 * knowledge_edges 表 —— 节点间有向关系（一等公民）。
 *
 * 6 种边类型（用 text + CHECK 跟项目惯例）：
 * - references：一般引用（[[wikilink]] 自动产生）
 * - supersedes：新节点推翻旧节点（维持时间线）
 * - merged_from：新节点合并自多个旧节点
 * - derived_from：lesson → rule 升级派生
 * - conflicts_with：冲突，待人审裁决
 * - promoted_to：层级提升记录
 *
 * 约束（SQL 层加 CHECK + UNIQUE）：
 * - 自指禁止（from <> to）
 * - 同方向同类型唯一（(from, to, edge_type) UNIQUE）
 */
export const knowledgeEdges = pgTable(
  "knowledge_edges",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    fromNodeId: uuid("from_node_id")
      .notNull()
      .references(() => knowledgeNodes.id, { onDelete: "cascade" }),
    toNodeId: uuid("to_node_id")
      .notNull()
      .references(() => knowledgeNodes.id, { onDelete: "cascade" }),
    /** references | supersedes | merged_from | derived_from | conflicts_with | promoted_to */
    edgeType: text("edge_type").notNull(),
    createdByAgent: uuid("created_by_agent").references(() => agents.id, {
      onDelete: "set null",
    }),
    createdByUser: text("created_by_user").references(() => authUsers.id, {
      onDelete: "set null",
    }),
    /** true 表示来自 [[node-id]] 自动解析（NodeWriter）；false 表示显式 API 加边 */
    autoGenerated: boolean("auto_generated").notNull().default(false),
    metadata: jsonb("metadata").notNull().default(sql`'{}'::jsonb`),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    /** 正向遍历："我引用了谁" */
    fromTypeIdx: index("knowledge_edges_from_type_idx").on(table.fromNodeId, table.edgeType),
    /** 反向遍历："谁引用了我" */
    toTypeIdx: index("knowledge_edges_to_type_idx").on(table.toNodeId, table.edgeType),
    /** 同方向同类型唯一（A→B references 仅一条；A→B 同时 references+supersedes 合法） */
    uniqueDirected: uniqueIndex("knowledge_edges_unique_directed").on(
      table.fromNodeId,
      table.toNodeId,
      table.edgeType,
    ),
  }),
);
